CREATE TABLE WYDAWCY (
    ID_WYDAWCY CHAR(10) PRIMARY KEY,
    NAZWA_WYDAWCY VARCHAR(35),
    STRONA_INTERNETOWA CHAR(40) CHECK (CHARINDEX('@', STRONA_INTERNETOWA) > 0)
);

CREATE TABLE KSIAZKI (
    ID_KSIAZKI CHAR(10) PRIMARY KEY,
    TYTUL VARCHAR(30) NOT NULL,
    ROK_WYDANIA INT CHECK (ROK_WYDANIA > 0 AND ROK_WYDANIA < YEAR(GETDATE())),
	ILOSC_DOSTEPNYCH_KOPII INT CHECK(ILOSC_DOSTEPNYCH_KOPII>=0),
	ID_WYDAWCY CHAR(10) REFERENCES WYDAWCY ON UPDATE CASCADE
);

CREATE TABLE AUTORZY(
	ID_AUTORA CHAR(10) PRIMARY KEY,
	IMIE VARCHAR(20) NOT NULL CHECK (ASCII(LEFT(IMIE, 1)) BETWEEN 65 AND 90 AND ISNUMERIC(IMIE)=0),
	NAZWISKO VARCHAR(20) CHECK (LEFT(NAZWISKO, 1) = UPPER(LEFT(NAZWISKO, 1)) AND ISNUMERIC(NAZWISKO)=0),
	DATA_URODZENIA DATE
);

CREATE TABLE GATUNKI (
	NAZWA CHAR(40) PRIMARY KEY NOT NULL,
	OPIS_GATUNKU CHAR(100)
);

CREATE TABLE OPINIE(
	ID_OPINII INT PRIMARY KEY IDENTITY(1,1),
	TEKST_OPINII CHAR(100),
	OCENA INT CHECK (OCENA >= 0 AND OCENA <= 5) NOT NULL,
	AUTOR CHAR(20) NOT NULL,
	DATA_DODANIA_OPINII DATE NOT NULL,
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI ON UPDATE CASCADE NOT NULL
);

CREATE TABLE BESTSELLERY(
	ID_LISTY_BESTSELLEROW CHAR(10) PRIMARY KEY,
	DATA_WEJSCIA_NA_LISTE_BESTSELLEROW DATE NOT NULL
);

CREATE TABLE CZYTELNICY (
	PESEL CHAR(11) CHECK (LEN(PESEL) = 11 AND ISNUMERIC(PESEL) = 1) PRIMARY KEY,
	IMIE CHAR(15) NOT NULL CHECK (ASCII(LEFT(IMIE, 1)) BETWEEN 65 AND 90 AND ISNUMERIC(IMIE)=0) ,
	NAZWISKO CHAR(15) NOT NULL CHECK (ASCII(LEFT(NAZWISKO, 1)) BETWEEN 65 AND 90 AND ISNUMERIC(NAZWISKO)=0),
	NUMER_TELEFONU CHAR(9) NOT NULL CHECK(LEN(NUMER_TELEFONU)=9 AND ISNUMERIC(NUMER_TELEFONU)=1),
	ADRES_E_MAIL VARCHAR(40) CHECK (CHARINDEX('@', ADRES_E_MAIL) > 0),
	WOJEWODZTWO VARCHAR(25) CHECK (WOJEWODZTWO IN (
        'Dolnoœl¹skie',
        'Kujawsko-Pomorskie',
        'Lubelskie',
        'Lubuskie',
        '£ódzkie',
        'Ma³opolskie',
        'Mazowieckie',
        'Opolskie',
        'Podkarpackie',
        'Podlaskie',
        'Pomorskie',
        'Œl¹skie',
        'Œwiêtokrzyskie',
        'Warmiñsko-Mazurskie',
        'Wielkopolskie',
        'Zachodniopomorskie'
    )) NOT NULL,
	MIASTO VARCHAR(20) NOT NULL CHECK(ISNUMERIC(MIASTO) = 0),
	ULICA VARCHAR(20) NOT NULL,
	NUMER_DOMU_MIESZKANIA VARCHAR(10) CHECK(ISNUMERIC(NUMER_DOMU_MIESZKANIA) = 1),
	KOD_POCZTOWY VARCHAR(6)
);

CREATE TABLE WYPOZYCZENIA(
	ID_WYPOZYCZENIA CHAR(10) PRIMARY KEY,
	DATA_WYPOZYCZENIA DATE CHECK (YEAR(DATA_WYPOZYCZENIA) > 1900) NOT NULL,
	PLANOWANA_DATA_ZWROTU DATE CHECK (YEAR(PLANOWANA_DATA_ZWROTU) > 1900) NOT NULL,
	DATA_ZWROTU DATE CHECK (YEAR(DATA_ZWROTU) > 1900),
	PESEL CHAR(11) REFERENCES CZYTELNICY ON UPDATE CASCADE NOT NULL,
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI ON UPDATE CASCADE NOT NULL
);

CREATE TABLE REZERWACJE(
	ID_REZERWACJI CHAR(10) PRIMARY KEY,
	DATA_REZERWACJI DATE CHECK (YEAR(DATA_REZERWACJI) > 1900) NOT NULL,
	PLANOWANA_DATA_ODBIORU DATE CHECK (YEAR(PLANOWANA_DATA_ODBIORU) > 1900) NOT NULL,
	STATUS_REZERWACJI VARCHAR(30) CHECK (STATUS_REZERWACJI IN(
		'Aktywna',
		'Odebrana',
		'Anulowana',
		'Nieodebrana w terminie',
		'W trakcie przetwarzania',
		'Wstrzymana',
		'W oczekiwaniu na ksi¹¿kê'
	)),
	PESEL CHAR(11) REFERENCES CZYTELNICY ON UPDATE CASCADE NOT NULL,
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI ON UPDATE CASCADE NOT NULL
);


CREATE TABLE AUTORZY_KSIAZEK(
	ID_AUTORA CHAR(10) REFERENCES AUTORZY ON UPDATE CASCADE,
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI ON UPDATE CASCADE,
	PRIMARY KEY (ID_AUTORA, ID_KSIAZKI)
);

CREATE TABLE GATUNKI_KSIAZEK(
	NAZWA_GATUNKU CHAR(40) REFERENCES GATUNKI(NAZWA) ON UPDATE CASCADE,
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI ON UPDATE CASCADE,
	PRIMARY KEY (NAZWA_GATUNKU, ID_KSIAZKI)
);

CREATE TABLE KSIAZKI_NA_LISCIE_BESTSELLEROW(
	ID_KSIAZKI CHAR(10) REFERENCES KSIAZKI(ID_KSIAZKI) ON UPDATE CASCADE,
	ID_LISTY_BESTSELLEROW CHAR(10) REFERENCES BESTSELLERY ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(ID_KSIAZKI, ID_LISTY_BESTSELLEROW)
);