CREATE VIEW WIDOK_KSIAZKI_AUTORZY AS
SELECT
    K.TYTUL,
    K.ROK_WYDANIA,
    STUFF((
        SELECT ', ' + A.IMIE + ' ' + A.NAZWISKO
        FROM AUTORZY_KSIAZEK AK
        JOIN AUTORZY A ON AK.ID_AUTORA = A.ID_AUTORA
        WHERE K.ID_KSIAZKI = AK.ID_KSIAZKI
        FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 2, '') AS AUTORZY
FROM
    KSIAZKI K;
